# Generated by Django 4.0 on 2023-06-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('MID', models.AutoField(primary_key=True, serialize=False, verbose_name='會員編號')),
                ('MPW', models.CharField(max_length=20, verbose_name='會員密碼')),
                ('MAC', models.CharField(max_length=50, verbose_name='會員帳號')),
            ],
        ),
    ]
