# Generated by Django 4.0 on 2023-06-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.CharField(max_length=10, verbose_name='產品編號')),
                ('PName', models.CharField(max_length=20, verbose_name='產品名稱')),
                ('PDetail', models.CharField(max_length=100, verbose_name='產品內容')),
            ],
        ),
    ]
